name: ASP.NET Order Processing CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Application
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0 # Change this if you're using a different version

      # Restore Dependencies
      - name: Restore Main Project Dependencies
        run: dotnet restore ./ASP.NET-Order-Processing-Application/ASP.NET-Order-Processing-Application.csproj

      # Step 4: Build the main project
      - name: Build Main Project
        run: dotnet build ./ASP.NET-Order-Processing-Application/ASP.NET-Order-Processing-Application.csproj --no-restore

      # Step 5: Restore dependencies for the test project
      - name: Restore Test Project Dependencies
        run: dotnet restore ./OrderProcessingTests/OrderProcessingTests.csproj

      # Step 6: Build the test project
      - name: Build Test Project
        run: dotnet build ./OrderProcessingTests/OrderProcessingTests.csproj --no-restore

      # Step 7: Run tests
      - name: Run Tests
        run: dotnet test ./OrderProcessingTests/OrderProcessingTests.csproj --no-build --verbosity normal

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Checkout the code again for deployment
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0 # Change this if you're using a different version

      # Publish the Application
      - name: Publish Application
        run: dotnet publish -c Release -o ./published

      # Example deployment step
      - name: Deploy to Server
        env:
          DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_KEY }} # Use secrets for sensitive data
        run: |
          echo "Deploying application..."
          # Replace this with your deployment script, e.g., copying to a server or Azure deployment
